### ISSUE TITLE
Can't make a move when the window is of a certain width

### ISSUE THREAD

**Issue by dcmoore** [miketabb33/speed-tic-tac-toe#4]
When the window shrinks beyond a point, even when it doesn't have a visual effect on the game, some squares become un-clickable.

**Comment by dcmoore** [comment]
It's important to test front-end code our in smaller windows when developing on a big monitor. The average person's screen size may run into this issue. We don't want to ship code that won't work for a large subset of our users.

**Comment by miketabb33** [comment]
Complete and responsive
