### ISSUE TITLE
Refactor long if/else chain

### ISSUE THREAD

**Issue by dcmoore** [miketabb33/speed-tic-tac-toe#7]
https://github.com/miketabb33/speed-tic-tac-toe/blob/master/images/player-marker-image.tsx#L14-L29

Separate, but related; images should render just fine regardless of how this is implemented. You may need to dive in and figure out the core reason as to why images weren't rendering properly.

**Comment by miketabb33** [comment]
SOLVED: The source attribute of the images were capitalized, however, the image name was not capitalized. example: src = "/player-marker/X.png" but the image name was x.png. 
Everything worked fine in the local dev environment but broke in the production environment.
